<?php

return [
    'CATEGORY_IMG_PATH' => '/category/',
    'SLIDER_IMG_PATH' => '/slider/',
    'NOTIFICATION_IMG_PATH' => '/notification/',
    'USER_IMG_PATH' => '/users/',
    'CHAT_FILE' => '/chat/',
    'CHAT_AUDIO' => '/chat_audio/',
    'PROPERTY_TITLE_IMG_PATH' => '/property_title_img/',
    'PROPERTY_GALLERY_IMG_PATH' => '/property_gallery_img/',
    'ARTICLE_IMG_PATH' => '/article_img/',
    'ADVERTISEMENT_IMAGE_PATH' => '/advertisement_img/',
    "IMG_PATH" => '/images',
    'PARAMETER_IMG_PATH' => '/parameter_img/',
    '3D_IMG_PATH' => '/3d_img/',
    'PARAMETER_IMAGE_PATH' => '/parameter_img/',
    'FACILITY_IMAGE_PATH' => '/facility_img/',

    "JSON_PATH" => '/json',

    //HuyTBQ: Parameter for properties on properties card
    'code_title' => 'Mã BDS',
    'area_title' => 'Diện tích',
    'price_range_title'=> 'Mức giá',
    'area' => '15',
    'max_area' => '1000',
    'number_floor_title'=>'Số tầng',
    'number_floor'=>'18',
    'number_room_title'=>'Số phòng',
    'number_room'=>'19',
    
    'legal_title' => 'Pháp lý',
    'legal' => '13',
    'direction_title' => 'Hướng',
    'direction' => '12',
    'road_width_title' => 'Đường rộng',
    'road_width' => '10',
    'price_m2_title' => 'Giá m2',
    'price_m2' => '16',
    'max_price' => '50000000000',
    'bathroom_title' => 'Nhà vệ sinh',
    'bathroom' => '4',
    'garage_title' => 'Gara đổ xe - chỗ đậu xe',
    'garage' => '17',
    'pool_title' => 'Hồ bơi',
    'pool' => '11',
    'furniture_title' => 'Nội thất',
    'furniture' => '8',
    'construction_status_title' => 'Tình trạng xây dựng',
    'construction_status' => '7',
    'rental_period_title' => 'Thời hạn thuê',
    'rental_period' => '3',
];
