<?php

return [
    'IMG_PATH'                  => '/images',
    'CATEGORY_IMG_PATH'         => '/category/',
    'SLIDER_IMG_PATH'           => '/slider/',
    'USER_IMG_PATH'             => '/users/',
    'PROPERTY_TITLE_IMG_PATH'   => '/property_title_img/',
    'PROPERTY_GALLERY_IMG_PATH' => '/property_gallery_img/',
    'STATION_IMG_PATH'          => '/stations/',

    'JSON_PATH' => '/json',

    // Property display parameters (used by landing page property cards)
    'code_title' => 'Mã BDS',
    'area_title' => 'Diện tích',
    'price_range_title'=> 'Mức giá',
    'area' => '15',
    'max_area' => '1000',
    'number_floor_title'=>'Số tầng',
    'number_floor'=>'18',
    'number_room_title'=>'Số phòng',
    'number_room'=>'19',
    
    'legal_title' => 'Pháp lý',
    'legal' => '13',
    'direction_title' => 'Hướng',
    'direction' => '12',
    'road_width_title' => 'Đường rộng',
    'road_width' => '10',
    'price_m2_title' => 'Giá m2',
    'price_m2' => '16',
    'max_price' => '50000000000',
    'bathroom_title' => 'Nhà vệ sinh',
    'bathroom' => '4',
    'garage_title' => 'Gara đổ xe - chỗ đậu xe',
    'garage' => '17',
    'pool_title' => 'Hồ bơi',
    'pool' => '11',
    'furniture_title' => 'Nội thất',
    'furniture' => '8',
    'construction_status_title' => 'Tình trạng xây dựng',
    'construction_status' => '7',
    'rental_period_title' => 'Thời hạn thuê',
    'rental_period' => '3',
];
